String address = "Wijnhaven 107";
String plaats = "Rotterdam";
int devicenr = 8;
String anaam = "de Raaf";
String initialen = "C";
int bedrag = 100;
String bericht = "U heeft geld opgenomen";
int tijdUren = 16;
int tijdMinuten = 57;
